language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t auotila/docker-react -f Dockerfile.dev .

foo-script:
    - docker run -e CI=true USERNAME/docker-react npm run test