language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t auotila/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true auotila/docker-react npm run test